name: merlincamozzi
favicon: null
layout_spectrum: 0.38580714678391814
typography_spectrum: 0.8669209429062903
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.20592523296363652
  lightness: 0.9696166850626469
  saturation: 0.6402922621928155
  rhythmicContrast: 0.27684270846657455
purpose: []
